### ISSUE TITLE
4 Modelling

### ISSUE THREAD

**Issue by z5389733** [z5429207/ZZSC9020-Group-P#7]
GanttStart: 2024-03-25
GanttDue: 2024-04-07
### Description
This is a high level issue to track all activities within the Modelling phase of the CRISP-DM framework for Group P's Project.

### Task List

- [ ] Describe Modelling Methods
- [ ] Build Multiple Models
- [ ] Create Test / Training datasets
- [ ] Visualisation of tasks
- [x] #26
