### ISSUE TITLE
5 Evaluation

### ISSUE THREAD

**Issue by z5389733** [z5429207/ZZSC9020-Group-P#8]
GanttStart: 2024-04-08
GanttDue: 2024-04-16
### Description
This is a high level issue to track all activities within the Evaluation phase of the CRISP-DM framework for Group P's Project.

### Task List

- [x] #20
- [ ] Describe metrics used
- [ ] Visualisation of metrics
- [ ] Visualisation of trained model
- [ ] Statistical Tests
- [ ] Discussion
- [x] #27
